version: "3.8"

services:
  django:
    container_name: django-container
    build:
      context: ./connectedhealth
    command: >
      sh -c "python manage.py migrate &&
             python3 manage.py makemigrations &&
             ./startserverdocker"
    ports:
      - 8000:8000
    volumes:
      - ./connectedhealth:/app
    stdin_open: true
    tty: true
  react-native:
    container_name: react-native-container
    build:
      context: ./ExpoCAMwithTensor
    # command: >
    #   sh -c "npx expo start"
    ports:
      - 19000:19000
    volumes:
      - ./ExpoCAMwithTensor:/app
      - /app/node_modules
    stdin_open: true
    tty: true
