version: "3.8"

services:
  django:
    container_name: django-container
    build:
      context: ./connectedhealth
    command: >
      sh -c "python manage.py migrate &&
             python3 manage.py makemigrations &&
             cat ip.txt &&
             python3 manage.py runserver"
    ports:
      - 8000:8000
    volumes:
      - ./connectedhealth:/app
    tty: true
